### ISSUE TITLE
Does not work with MAMP Pro although Chrome Ext Works

### ISSUE THREAD

**Issue by smlombardi** [edge-code/edge-inspect-extension#2] opened 2013-06-20 18:12 UTC
Unless I have done it wrong. My setup works with Chrome and the Edge Inspect Plugin, using the instructions from xp.io

Here's my setup: Mac 10.8.4, MAMP Pro.  IP address for WIFI is 192.168.001.56, wired is 172.30.001.9. I found that to make the Chrome Edge Inspect work I needed to set MAMP to have a server alias set up via xp.io.  I open this url (mysite.192.168.001.56.xip.io) in Chrome, click the extension, and the page opens on the iPad. Perfect.

However, I have tried opening this site's "index.html" in Brackets 26, click the extension icon,connect to the iPad. Nothing. 

By copying and pasting the URL from the iPad's Edge Inspect CC app, the URL it is trying to load is 172.30.001.9:65492/index.html  This is obviously not going to load anything, it needs to go via the server alias, mysite.192.168.001.56.xip.io

**Comment by iwehrman** [comment] 2013-06-21 18:48
Hi there! Sadly, it is a known issue with Edge Code extension that it may fail if the machine has multiple non-local IP addresses. Does it work if you disable your wired interface?

**Comment by iwehrman** [comment] 2013-06-21 18:50
Also, the Edge Code extension includes its own HTTP server, and will only ever direct your remote devices to that server. So the trick will be to get your remote devices to connect directly to your wifi IP address.

**Comment by iwehrman** [comment] 2013-07-08 17:13
Closing because this seems to be a known issue. If the issue is different from the one described above, please re-open!

**Closed as completed by iwehrman** 2013-07-08 17:13 UTC
